#!/usr/bin/python3
import os
import signal
import mariadb
from time import sleep
from datetime import datetime
from medmag import Medmag

dispense = 0

def mariadb_connection():
    try:
        conn = mariadb.connect(
                user = "root",
                password = "G0dH@d3s",
                host = "127.0.0.1",
                port = 3306,
                database = "capstone"
        )
    except mariadb.Error as e:
        print(f"Error connecting to MariaDB Platform: {e}")
        sys.exit(1)
    
    return conn.cursor()

m = Medmag()
while True:
    cur = mariadb_connection()
    try:
        cur.execute("SELECT * FROM medicine")
    except:
        print(f"Error pulling information from MariaDB: {e}")
    
    # Get current time to the nearest minute
    n = datetime.now()
    current_time = n.strftime("%H:%M")

    # Pull information from database
    for row in cur:
        med_time = ":".join(str(row[2]).split()[1].split('.')[0].split(':')[0:2])
        if (current_time == med_time):
            dispense = 1
            break

    cur.close()
    sleep(2)

    # Time to dispense medication
    if (dispense == 1):
        print("Time to Dispense!")
    

    b = os.fork()
    if (b == 0):
        m.breath()
        os.kill(b,signal.SIGKILL)

    a = os.fork()
    if (a == 0):
        m.audio()
        os.kill(a,signal.SIGKILL)
    
    while (not m.button_control()):
        pass
    
    motor = os.fork()
    if (motor == 0):
        m.motor()
        os.kill(motor,signal.SIGKILL)

    dispense = 0
    sleep(60)


